include: package:lints/recommended.yaml

analyzer:
  exclude: [example/explorer/**]
  language: 
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors: 
    todo: ignore
      
linter:
  rules:
    # Some additional lints we want to enforce
    always_declare_return_types: true
    cascade_invocations: true
    directives_ordering: true
    omit_local_variable_types: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true

    # This is a good lint, but
    # https://github.com/microsoft/win32metadata/issues/99 makes it impossible
    # to resolve today.
    library_private_types_in_public_api: false

    # We name Win32 constants for consistency with Win32, not Dart
    constant_identifier_names: false
    non_constant_identifier_names: false
    camel_case_types: false

    # COM interop classes are named for their contents
    file_names: false

    # Unnecessary in most cases, but avoids accidental name clashes.
    unnecessary_this: false

    # Lints coming in lints 2.0 that we can turn on now
    # TODO: Remove this section when we update to Dart 2.17
    depend_on_referenced_packages: true
    null_check_on_nullable_type_parameter: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_constructor_name: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_nullable_for_final_variable_declarations: true